### PR TITLE
Implemented and wrote tests for Entity class. 

### PR DESCRIPTION
**Pull request by OwaisZ1**
Pretty much the title.

### CODE REVIEW

**Comment by tseamuscorlett** [comment]
You guys should add more Javadoc! Otherwise I think it looks good in terms of CA/SOLID

**Comment by enerko** [comment]
Are there no ways to separate your work into two branches? I know that you have overlapping sections, but it would most likely cause problems in the future if both of you push onto the same branch (you would need to merge in order to push) which is a lot of extra work.

**Comment by enerko** [comment]
Everything other than what I mentioned seems to be good. The pull request title is not very accurate now so could you either edit the title or close the pull request and create a new one before merging?

**Comment by enerko** [comment]
Also could you add packaging within each architecture layers for your section (e.g."entities/login_registeration") to avoid confusion?

**Pull request closed without merging**
